import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/app/_components/wrapper/Navbar";
import { Layout } from "@/components/ds";

const montserrat = Montserrat({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Layout>
            <body className={`${montserrat.className} antialiased`}>
                <Navbar />
                {children}
            </body>
        </Layout>
    );
}
